# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the soft cluster assignments of query cells across reference clusters.
#' 
#' @param Y Reference cluster centroid locations
#' @param Z Query cells projected into PC space (d x m)
#' @param sigma Soft k-means "fuzziness" parameter, sigma = 0 is hard clustering
#' @export
soft_cluster <- function(Y, Z, sigma) {
    .Call('_symphony_soft_cluster', PACKAGE = 'symphony', Y, Z, sigma)
}

#' Computes the Symphony reference compression terms, Nr and C.
#' 
#' @param Rr Soft cluster assignments of reference cells (cols) across clusters (rows).
#' @param Zr Corrected embedding for reference cells (cols) in harmonized PCs (rows).
#' @export
compute_ref_cache <- function(Rr, Zr) {
    .Call('_symphony_compute_ref_cache', PACKAGE = 'symphony', Rr, Zr)
}

#' Computes the corrected query cell embedding.
#' 
#' @param Zq Query cells projected into PC space (d x m)
#' @param Xq Query design matrix ((c + 1) x m)
#' @param Rq Query soft cluster assignments across reference clusters (k x m)
#' @param Nr Reference cluster sizes (first compression term) (length k)
#' @param RrZtr Second reference compression term (C) (k x d)
#' @export
moe_correct_ref <- function(Zq, Xq, Rq, Nr, RrZtr) {
    .Call('_symphony_moe_correct_ref', PACKAGE = 'symphony', Zq, Xq, Rq, Nr, RrZtr)
}

#' Returns the batch coefficients of the linear mixture model as a 3D tensor.
#' 
#' @param R Cell cluster assignments
#' @param Z PCA embedding
#' @param lambda Diagonal matrix for ridge regression
#' @param design Design matrix
#' @export
get_betas <- function(R, Z, lambda, design) {
    .Call('_symphony_get_betas', PACKAGE = 'symphony', R, Z, lambda, design)
}

